services:
  db:
    image: mariadb:10.7
    working_dir: /application
    command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1 ]
    volumes:
      - recruitment-task-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: cargo
      MYSQL_USER: cargo
      MYSQL_PASSWORD: cargo

  nginx:
    image: nginx:stable-alpine
    container_name: recruitment-task-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
      args:
        UID: "1000"
        GID: "1000"
    user: "1000:1000"
    container_name: recruitment-task-php
    volumes:
      - .:/var/www/html:cached

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ROOT
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_USER: root
      MYSQL_PASSWORD: ROOT
    ports:
      - '8080:80'


volumes:
  recruitment-task-db: